- name: Install Apache on EC2
  hosts: vm01
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        state: latest
        force_apt_get: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present  
      notify: done

  handlers:  
    - name: done
      service:
        name: apache2
        state: started
        enabled: yes
