- name: my first playbook
  hosts: vm01
  become: true
  tasks:
  - name: Print message
    debug: 
     msg: hello world
  - name: copy file
    copy: 
      src: ./text1.txt
      dest: /home/ubuntu/
  - name: create a file
    command: mkdir /home/ubuntu/aayush2
  
  - name: install nginx
    apt: 
       name: nginx 
       state: present
       update_cache: yes
